image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
dpi_val : 300
summary_plots : true
print_summary: true

evaluation:
  metrics  : ["rmse", "mae"]
  regions: ["global", "nhem"]
  summary_dir: "./plots/"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  print_summary: false #print out score values on screen. it can be verbose

run_ids :

  ndl2qget :  # Inference run id.
    label: "One-shot LST prediction"
    mini_epoch: 0
    rank: 0
    streams:
      SEVIRI_LST:
        channels: ["LST"] #["2t", "q_850", ] #["LST"] # ["LST"] #["2t", "q_850", ]
        evaluation:
          sample: "all"
          forecast_step: "all"
        plotting:
          sample: [0, 1]
          forecast_step: [ 1, 2, 3, 4, 5, 6] #, 2, 3, 4] #, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
          plot_maps: true
          plot_histograms: true