ERA5 :
  type : anemoi
  filenames : ['aifs-ea-an-oper-0001-mars-o96-1979-2023-6h-v8.zarr']
  stream_id : 0
  source_exclude : ['w_', 'skt', 'tcw', 'cp', 'tp']
  target_exclude : ['w_', 'slor', 'sdor', 'tcw', 'cp', 'tp']
  loss_weight : 1.
  location_weight : cosine_latitude
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 8
  tokenize_spacetime : True
  max_num_targets: -1 
  forcing: True
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 8
    dim_embed : 512
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 512
  target_readout :
    num_layers : 2
    num_heads : 4
    # sampling_rate : 0.2
  pred_head :
    ens_size : 1
    num_layers : 1