# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.


SEVIRI_LST :
  type : msg_lst
  filenames : ['mpg_seviri_l2_2017-18_v0/lst_test.zarr'] # use ['mpg_seviri_l2_2017-18_v0/seviri.zarr'] after zarr3 is enabled
  data_start_time : "2017-01-01 00:00"
  data_end_time : "2017-09-30 00:00"
  target: ["LST"]
  source: ["LST"]
  geoinfos: ["DEM"] #, "LANDCOV"]
  metadata: "/leonardo_work/AIFAC_5C0_154/weathergen/data/mpg_seviri_l2_2017-18_v1/metadata" # uses one scene over south africa for finetuning 
  loss_weight : 1.0
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 64
  tokenize_spacetime : True
  max_num_targets: -1 #-1
  val_source_channels: ["LST"]
  val_target_channels: ["LST"]
  embed :
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    type : 'obs_value'
    num_layers : 2
    num_heads : 4
  pred_head :
    ens_size : 1
    num_layers : 1