SEVIRI_LST :
  type : msg_lst
  filenames : ['mpg_seviri_2017_lst_v0']
  data_start_time : "2017-01-01 00:00"
  data_end_time : "2017-12-31 00:00"
  source_exclude: []
  target_exclude: ["LANDCOV", "quality_flag", "DEM", "FVC", "LW_MASK"]
  target: ["LST"]
  metadata: "/p/scratch/weatherai/shared/weather_generator_data/mpg_seviri_2017_lst_v0/metadata"
  experiment: "johannesburg"
  loss_weight : 1.0
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 64
  tokenize_spacetime : True
  max_num_targets: -1
  embed :
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    type : 'obs_value'
    num_layers : 2
    num_heads : 8
  pred_head :
    ens_size : 1
    num_layers : 1