SEVIRI_LST :
  type : msg_lst
  stream_id: 1
  filenames : ['mpg_seviri_l2_2017-18_v0/lst_test.zarr'] # use ['mpg_seviri_l2_2017-18_v0/seviri.zarr'] after zarr3 is enabled
  data_start_time : "2017-02-01 00:00"
  data_end_time : "2017-06-30 00:00"
  target: ["LST"]
  source: []
  geoinfos: [] #["DEM"] #, "LANDCOV"]
  metadata: "/leonardo_work/AIFAC_5C0_154/weathergen/data/mpg_seviri_l2_2017-18_v1/metadata" # uses one scene over south africa for finetuning 
  scene: "scenes_train_scene_001.npz"
  spatial_stride: 24
  temporal_stride: 6
  sampling_rate_target: 0.005  # use 10% of spatial points
  loss_weight : 1.0
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 64
  tokenize_spacetime : True
  max_num_targets: -1 #-1
  embed :
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 16
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 16
  target_readout :
    type : 'obs_value'
    num_layers : 2
    num_heads : 4
  pred_head :
    ens_size : 1
    num_layers : 1